export const $arenas = document.querySelector(".arenas")
export const $formFight = document.querySelector(".control")
export const $fightButton = document.querySelector(".button")
export const $chat = document.querySelector(".chat")
export const $hit = document.getElementById("audio-hit")
export const $block = document.getElementById("audio-block")
